name: 'Terraform Unit Tests'

on:
  push:

jobs:
  terraform-unit-tests:
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-unit-test.yml@AWSv1
    name: 'Terraform Unit Tests'
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
      SKIP_CHECKS: CKV_AWS_273,CKV_AWS_356,CKV_AWS_109
